[package]
name = "Library"
version = "0.1.0"
authors = ["chicken1925 <cinderella6591.gray@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
